# All-In-One 模块配置文件
# 如果配置错误模块会使用默认配置
# 会自动输出模块日志到 config.yaml.log
# 修改完之后记得重启喔
# Ciallo～ (∠・ω< )⌒☆

# CPU 分配
# 用户后台应用（推荐: 0-1）
用户后台应用 0-1
# 系统后台应用（推荐: 0-2）
系统后台应用 0-2
# 前台应用（推荐: 0-7）
前台应用 0-7
# 上层应用（也就是悬浮窗啦）（推荐: 0-7）
上层应用 0-7

# CPU 负载均衡（推荐: 核心均衡）
# 0: 核心均衡
# 1: 软件均衡
负载均衡 0

# 性能调节（推荐：性能优先）
# 0: 性能优先（释放设备大部分性能）
# 1: 省电优先（使用保守策略配置）
# 2: 超级省电（强制使用省电配置）
# 3: 养老模式（关闭超频调度等功能, 仅对系统进行优化）
性能调节 0


# 额外选项
# 这里是额外选项喔
# 看看里面有没有你中意的功能喔
# Ciallo～ (∠・ω< )⌒☆

# 王者 O3T/VT 帧率优化
# 原理: 更改王者荣耀 OpenGLES3Config.xml 配置文件
# 0: 默认模式（不修改）
# 1: 开启 O3T 模式
# 2: 开启 VT 模式
# 3: 删除 O3T/VT 配置文件
王者优化 0

# TCP 网络优化（默认推荐: 1）
# 0: 关闭网络优化
# 1: 开启网络优化
TCP网络优化 1

# 移除小米更新验证（适用于MIUI）
# 0: 关闭移除小米更新验证功能
# 1: 开启移除小米更新验证功能
移除小米更新验证 0

# 禁用模块日志输出（默认: 0）
# 0: 输出默认日志
# 1: Ciallo～ (∠・ω< )⌒☆
# 2: 禁用日志功能
模块日志输出 0

# 大小核调度
# 安卓系统将 CPU 分成了大小核两部分
# 大核适用于处理运行游戏或视频处理等高强度任务
# 小核适用于处理大部分音频播放、网页滚动、操作系统等低强度任务
# 适当调整大小核调度可以提升设备的性能/续航
# Tips: 默认禁用自定义大小核调度, 采用性能调节推荐的配置
# 更改 none 为其他值则表示启用
# Ciallo～ (∠・ω< )⌒☆

# 大核调度（提高这个值有利于性能，不利于降低功耗）
# 默认推荐: 40 40
大核调度 none
# 小核调度（提高这个值不利于性能，有利于降低功耗）
# 默认推荐: 60 60
小核调度 none
