# All-In-One 模块配置文件
# 如果配置错误模块会使用默认配置
# 会自动输出模块日志到这里
# 修改完之后记得重启喔
# Ciallo～ (∠・ω< )⌒☆

# CPU 分配
# 用户后台应用（推荐: 0-1）
用户前台应用 0-1
# 系统后台应用（推荐: 0-2）
系统后台应用 0-2
# 前台应用（推荐: 0-7）
前台应用 0-7
# 上层应用（也就是悬浮窗啦）（推荐: 0-7）
上层应用 0-7

# CPU 负载均衡（推荐: 核心均衡）
# 0: 核心均衡
# 1: 软件均衡
负载均衡 0

# 性能调节（推荐：性能优先）
# 0: 性能优先
# 1: 省电优先
# 2: 超级省电（强制使用省电配置）
性能调节 0